# Скачивает все документы МБОУ «СШ № 56» в подпапки по категориям.
# Запуск в PowerShell:  powershell -ExecutionPolicy Bypass -File '.\Скачать всё (Windows).ps1'

$ErrorActionPreference='SilentlyContinue'
$UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0 Safari/537.36'
$items=@(
  @{c='01 Основные документы'; n='Выписка из государственной информационной системы «Реестр организаций, осуществляющих образовательну.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Reestrovaya_vypiska.pdf'},
  @{c='01 Основные документы'; n='Изменения и дополнения в коллективный договор №21 22 - 61 на 2025-2028 годы.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Izmeneniya_v_KD.pdf'},
  @{c='01 Основные документы'; n='Календарный учебный график на 2025 - 2026 учебный год МБОУ «Средняя школа №56».docx'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Kalendarnyy_grafik_25_26.docx'},
  @{c='01 Основные документы'; n='Коллективный договор.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Kollektivnyy_dogovor_2025.pdf'},
  @{c='01 Основные документы'; n='Лицензия на осуществление образовательной деятельности.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/licenzia_2015.pdf'},
  @{c='01 Основные документы'; n='Правила внутреннего распорядка обучающихся.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/pol_o_pravilax_vro.pdf'},
  @{c='01 Основные документы'; n='Правила внутреннего трудового распорядка.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Pravila_VNUTR_TRUD.RASPORYaDKA_NOVAYa_REDAKTsIYa.pdf'},
  @{c='01 Основные документы'; n='Приказ о проведении школьного этапа ВсОШ 23 24.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Prikaz_209_OD_ob_organizatsii_shk_etapa_VSOSh_23_24.pdf'},
  @{c='01 Основные документы'; n='Программа развития 2021-2026.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/programma_razvitiya_2021.pdf'},
  @{c='01 Основные документы'; n='Устав образовательной организации.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Ustav_2025_podpisan_ETsP.pdf'},
  @{c='01 Основные документы'; n='УЧЕБНЫЙ ПЛАН МБОУ «СШ № 56» на 2025 – 2026 учебный год.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/UChE_NYY_PLAN_2025_26_konstruktor.pdf'},
  @{c='02 Публичные отчёты'; n='Публичный доклад за 2025-2026 учебный год.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/_Publichnyy_doklad_2025_2026.pdf'},
  @{c='03 Финансово-хозяйственная деятельность'; n='Муниципальное задание на 2025 год.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/MZ_shkola_56_00000007_.pdf'},
  @{c='03 Финансово-хозяйственная деятельность'; n='Отчет ФХД по итогам 2025 года.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Otchet_FHD_2025.pdf'},
  @{c='03 Финансово-хозяйственная деятельность'; n='План финансово-хозяйственной деятельности на 2026 год.pdf'; u='https://school56.gosuslugi.ru/netcat_files/35/1620/plan_FHD_30.12.25.pdf'},
  @{c='04 Защита персональных данных'; n='Политика в отношении обработки персональных данных.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Politika_v_otnoshenii_obrabotki_personal_nyh_dannyh2.pdf'},
  @{c='05 Памятки'; n='Памятка для родителей о правильном питании школьников.pdf'; u='https://school56.gosuslugi.ru/netcat_files/105/2831/pamyatka_roditely.pdf'},
  @{c='05 Памятки'; n='Памятка Правила здорового питания.pdf'; u='https://school56.gosuslugi.ru/netcat_files/105/2831/Pamyatka_Pravila_zdorovogo_pitaniya_dlya_shkolmznikov71b6e.pdf'},
  @{c='05 Памятки'; n='Правила заполнения бланков ЕГЭ.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/10._pravila_zapolneniya_blankov_ege_v_2023_godu.pdf'},
  @{c='05 Памятки'; n='Профилактика алкоголизма среди подростков.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Profilaktika_alk_uch.pdf'},
  @{c='05 Памятки'; n='Профилактика подросткового суицида.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Profilaktika_rod.pdf'},
  @{c='06 Федеральные'; n='Приказ Минпросвещения РФ об утверждении порядка проведения аттестации.docx'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Prikaz_Minprosvescheniya_RF_ob_utverzhdenii_poryadka_provedeniya_attestatsii.docx'},
  @{c='06 Федеральные'; n='Федеральный государственный образовательный стандарт дошкольного образования.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Federal_nyy_gosudarstvennyy_obrazovatel_nyy_standart_doshkol_nogo_obrazovaniya.pdf'},
  @{c='07 Планы'; n='График оценочных процедур НОО 2 полугодие.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Grafik_otsenochnyh_protsedur_NOO_2_polugodie_23_24.pdf'},
  @{c='07 Планы'; n='График оценочных процедур ООО 1 полугодие 2025-2026.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/GO_OOO_2025_2026_1_polugodie.pdf'},
  @{c='07 Планы'; n='График оценочных процедур ООО 2 полугодие.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Graf_otsen_prots_OO_23_24_2polugod.pdf'},
  @{c='07 Планы'; n='График оценочных процедур СОО 1 полугодие 2025-2026.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/GO_SOO_2025_2026_1_polugodie.pdf'},
  @{c='07 Планы'; n='График оценочных процедур СОО 2 полугодие.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Grafik_otsen_prots_SO_23_24_2_polgod.pdf'},
  @{c='07 Планы'; n='Календарный план воспитательной работы на 2024-2025 учебный год.docx'; u='https://school56.gosuslugi.ru/netcat_files/32/50/_nash_Kalendarnyy_plan_vospitatel_noy_raboty24_25_1_.docx'},
  @{c='07 Планы'; n='Паспорт дорожной безопасности.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Pasport_dorozhnoy_bezopasnosti.pdf'},
  @{c='07 Планы'; n='План внеурочной деятельности МБОУ СШ №56.docx'; u='https://school56.gosuslugi.ru/netcat_files/32/50/_plan_vneurochnoy_deyatel_nosti1_11.docx'},
  @{c='07 Планы'; n='План мероприятий по профилактике экстремизма и терроризма.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Plan_meropriyatiy_po_profilaktike_extremizma_i_terrorizma.pdf'},
  @{c='07 Планы'; n='ПЛАН ОРГАНИЗАЦИОННО-ТЕХНИЧЕСКИХ МЕРОПРИЯТИЙ ПО УЛУЧШЕНИЮ УСЛОВИЙ ОХРАНЫ ТРУДА, ЗДОРОВЬЯ РАБОТАЮЩИХ И.docx'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Prikaz_200_od_ot_30.08.2024_Ob_utv._plana_OT_meropr._po_uluchsh._usl.OT.docx'},
  @{c='07 Планы'; n='План проведения месячника антинаркотической направленности и популяризации здорового образа жизни в.docx'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Plan_antinarkoticheskogo_mesyachnika.docx'},
  @{c='07 Планы'; n='Приказ 198 Об организации работ по снижению документационной и бюрократической нагрузки на педагогич.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Prikaz_198_Ob_organizatsii_rabot_po_snizheniyu_dokumentatsionnoy_i_byurokraticheskoy_nagruzki_na_pedagogicheskih_rabotnikov.pdf'},
  @{c='07 Планы'; n='Программа воспитания.docx'; u='https://school56.gosuslugi.ru/netcat_files/32/50/_nasha_programma_vospitaniya_shkoly56.docx'},
  @{c='07 Планы'; n='Программа воспитательной работы летнего пришкольного оздоровительного лагеря с дневным пребыванием д.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Programma_vospitatel_noy_raboty_letnego_prishkol_nogo_ozdorovitel_nogo_lagerya_s_dnevnym_prebyvaniem_detey_56.pdf'},
  @{c='07 Планы'; n='расписание кружков и секций на 2025-2026 учебный год.doc'; u='https://school56.gosuslugi.ru/netcat_files/32/50/raspisanie_kruzhkov_i_sektsiy_25_26.doc'},
  @{c='07 Планы'; n='Типовой план по снижению документационной и бюрократической нагрузки на педагогических работников.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Tipovoy_plan_po_snizheniyu_dokumentatsionnoy_i_byurokraticheskoy_nagruzki_na_pedagogicheskih_rabotnikov.pdf'},
  @{c='08 Отчёты'; n='Отчет о результатах самообследования за 2025 год.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/_Samoobsledovanie_za_2025.pdf'},
  @{c='10 Локальные нормативные акты'; n='Планы по устранению недостатков, выявленных в ходе независимой оценки качества.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/test_file_18.pdf'},
  @{c='10 Локальные нормативные акты'; n='Сведения о принятых по результатам проведения независимой оценки качества поощрительных мерах дисци.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/test_file_19.pdf'},
  @{c='10 Локальные нормативные акты'; n='Договор о сотрудничестве с ИГХТУ.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Dogovor_shkola_IGHTU.pdf'},
  @{c='10 Локальные нормативные акты'; n='Заявление на участие в индивидуальном отборе обучающихся в 10 класс.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/10_otbor.pdf'},
  @{c='10 Локальные нормативные акты'; n='Заявление о приеме в 10 класс.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Zayavlenie_o_prieme_v_10_klass.pdf'},
  @{c='10 Локальные нормативные акты'; n='Концепция информационной безопасности детей от 28.04.2023.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Kontseptsiya_ot_28.04.2023.pdf'},
  @{c='10 Локальные нормативные акты'; n='Локальный нормативный акт о языках обучения.doc'; u='https://school56.gosuslugi.ru/netcat_files/32/50/polozh_iaz.doc'},
  @{c='10 Локальные нормативные акты'; n='О мерах по обеспечению безопасности в период гололеда, образования наледи и сосулек на кровле школы.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Prikaz_08_OD_14.01.2025g._o_merah_po_obespechen.bezop.so_sl._pog.usl.GOLOLED.pdf'},
  @{c='10 Локальные нормативные акты'; n='Образец заявления о приеме на обучение.docx'; u='https://school56.gosuslugi.ru/netcat_files/32/50/2026._Z_A_Ya_V_L_E_N_I_E_v_1_klass.docx'},
  @{c='10 Локальные нормативные акты'; n='Педагогический состав 2026 по ОП.xlsx'; u='https://school56.gosuslugi.ru/netcat_files/171/3076/Kadry_na_sayt_2026_po_OP.xlsx'},
  @{c='10 Локальные нормативные акты'; n='Педагогический состав НОО.pdf'; u='https://school56.gosuslugi.ru/netcat_files/171/3076/Kadry_na_sayt_2026_po_OP_NOO.pdf'},
  @{c='10 Локальные нормативные акты'; n='Педагогический состав ООО.pdf'; u='https://school56.gosuslugi.ru/netcat_files/171/3076/Kadry_na_sayt_2026_po_OP_OOO.pdf'},
  @{c='10 Локальные нормативные акты'; n='Педагогический состав СОО.pdf'; u='https://school56.gosuslugi.ru/netcat_files/171/3076/Kadry_na_sayt_2026_po_OP_SOO.pdf'},
  @{c='10 Локальные нормативные акты'; n='Перечень юридических лиц и индивидуальных предпринимателей, оказывающих услуги по организации питани.xlsx'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Perechen_yuridicheskih_lits_i_individual_nyh_predprinimateley.xlsx'},
  @{c='10 Локальные нормативные акты'; n='Перечень юридических лиц и индивидуальных предпринимателей, поставляющих (реализующих) пищевые проду.xlsx'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Perechen_yuridicheskih_lits_i_individual_nyh_predprinimateley_0.xlsx'},
  @{c='10 Локальные нормативные акты'; n='План мероприятий по профилактике экстремизма.pdf'; u='https://school56.gosuslugi.ru/netcat_files/179/3093/plan_meropriyatiy_po_profilaktike_extremizma.pdf'},
  @{c='10 Локальные нормативные акты'; n='положение об оказании ПОУ.doc'; u='https://school56.gosuslugi.ru/netcat_files/32/50/polozhenie_ob_okazanii_POU_novoe.doc'},
  @{c='10 Локальные нормативные акты'; n='ПОЛОЖЕНИЕ О НАСТАВНИЧЕСТВЕ.docx'; u='https://school56.gosuslugi.ru/netcat_files/32/50/POLOZHENIE_O_NASTAVNICHESTVE.docx'},
  @{c='10 Локальные нормативные акты'; n='Положение о порядке применения в МБОУ «СШ № 56» сервисов взаимодействия педагогических работников с.docx'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Polozhenie_Sferum.docx'},
  @{c='10 Локальные нормативные акты'; n='Положение о режиме занятий обучающихся.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/p_rezhim_obuh_2018.pdf'},
  @{c='10 Локальные нормативные акты'; n='Положение о системе видеонаблюдения.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Polozhenie_o_sisteme_videonablyudeniya.pdf'},
  @{c='10 Локальные нормативные акты'; n='Положение об очно-заочной форме обучения.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Polozhenie_ob_ochno_zaochnoy_forme_obucheniya.pdf'},
  @{c='10 Локальные нормативные акты'; n='Положение об электронном обучении и использовании дистанционных образовательных технологий в образов.docx'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Polozhenie_ob_organizacii_obrazovatelnogo_processa_s_primeneniem_ehlektronnogo_obucheniya.docx'},
  @{c='10 Локальные нормативные акты'; n='Порядок и основания перевода, отчисления и восстановления обучающихся.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/pol_o_poryadke_perevoda_otcisteniya.pdf'},
  @{c='10 Локальные нормативные акты'; n='Порядок оформления возникновения, приостановления и прекращения отношений между образовательной орга.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/pol_o_poryadke_perevoda_otcisteniya_0.pdf'},
  @{c='10 Локальные нормативные акты'; n='Порядок проведения ГИА-9.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Poryadok_GIA9_2023.pdf'},
  @{c='10 Локальные нормативные акты'; n='Правила подачи апелляции.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Podacha_appelyatsii_v_2023g.pdf'},
  @{c='10 Локальные нормативные акты'; n='Правила приема обучающихся.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/pravila_priema_22.pdf'},
  @{c='10 Локальные нормативные акты'; n='ПРАВИЛА приема обучающихся в муниципальное бюджетное общеобразовательное учреждение «Средняя школа №.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/2._Pravila_priema_obuchayuschihsya_2023_2024_2_.pdf'},
  @{c='10 Локальные нормативные акты'; n='Предписания контрольно-надзорных органов, отчеты об их исполнении.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/akt_rpnz_170.pdf'},
  @{c='10 Локальные нормативные акты'; n='Приказ на изменение в положение об оплате учителей с 01.03.2025.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Prikaz_na_izmenenie_v_polozhenie_ob_olate_uchiteley_s_01.03.2025.pdf'},
  @{c='10 Локальные нормативные акты'; n='Приказ о внесении изменений в Положение о пропускном режиме.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Prikaz_o_vnesenii_izmeneniy_v_Polozhenie_o_propusknom_rezhime.pdf'},
  @{c='10 Локальные нормативные акты'; n='Приказ О сроках проведения индивидуального отбора в профильный класс в МБОУ «СШ № 56» для получения.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Prikaz_priem_v_10_klass.pdf'},
  @{c='10 Локальные нормативные акты'; n='Приказ об утверждении региональных инновационных площадок.pdf'; u='https://school56.gosuslugi.ru/netcat_files/180/3092/RIP_2026.pdf'},
  @{c='10 Локальные нормативные акты'; n='Проведение Всероссийских проверочных работ (ВПР).pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Poryadok_provedeniya_vserossiyskih_proverochnyh_rabot_v_2023_godu.pdf'},
  @{c='10 Локальные нормативные акты'; n='Распорядительный акт о закреплении организации за конкретными территориями.doc'; u='https://school56.gosuslugi.ru/netcat_files/32/50/postanovlenie_21.01.2013_o_zakreplenii_mikrouchastkov.doc'},
  @{c='10 Локальные нормативные акты'; n='Указ президента Российской Федерации «Об утверждении доктрины информационной безопасности Российской.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Ukaz.pdf'},
  @{c='10 Локальные нормативные акты'; n='Федеральный государственный образовательный стандарт начального общего образования.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Federal_nyy_gosudarstvennyy_obrazovatel_nyy_standart_nachal_nogo_obschego_obrazovaniya.docx.pdf'},
  @{c='10 Локальные нормативные акты'; n='Федеральный государственный образовательный стандарт основного общего образования.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Federal_nyy_gosudarstvennyy_obrazovatel_nyy_standart_osnovnogo_obschego_obrazovaniya.pdf'},
  @{c='10 Локальные нормативные акты'; n='Федеральный государственный образовательный стандарт среднего общего образования.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Federal_nyy_gosudarstvennyy_obrazovatel_nyy_standart_srednego_obschego_obrazovaniya.pdf'},
  @{c='10 Локальные нормативные акты'; n='Федеральный закон «О персональных данных».pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/152fz_O_persrnal_nyh_dannyh.pdf'},
  @{c='10 Локальные нормативные акты'; n='Форма апелляции о несогласии с выставленными баллами.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Forma_apellyatsii_o_nesoglasii_s_vystavlennymi_ballami.pdf'},
  @{c='10 Локальные нормативные акты'; n='Формы, периодичность и порядок текущего контроля успеваемости и промежуточной аттестации обучающихся.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/polojenit_usp_2022.pdf'},
  @{c='10 Локальные нормативные акты'; n='ЭКОНОМИКА_Результаты_школьного_этапа_ВсОШ.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/EKONOMIKA_Rezul_taty_shkol_nogo_etapa_VsOSh.pdf'},
  @{c='11 Платные образовательные услуги'; n='Образец договора об оказании платных образовательных услуг.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/dogovor22.pdf'},
  @{c='11 Платные образовательные услуги'; n='Порядок оказания платных образовательных услуг.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/polog_pou_22.pdf'},
  @{c='11 Платные образовательные услуги'; n='Утверждение стоимости обучения (по каждой образовательной программе).jpg'; u='https://school56.gosuslugi.ru/netcat_files/32/50/cci13122022_0002.jpg'},
  @{c='12 Прочие'; n='Английский язык_Результаты_школьного_этапа_ВсОШ.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Angliyskiy_yazyk.pdf'},
  @{c='12 Прочие'; n='География_Результаты_школьного_этапа_ВсОШ.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Geografiya.pdf'},
  @{c='12 Прочие'; n='Литература_Результаты_школьного_этапа_ВсОШ.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Literatura.pdf'},
  @{c='12 Прочие'; n='Меню приготавливаемых блюд для детей с 1 по 4 класс.xls'; u='https://school56.gosuslugi.ru/netcat_files/49/484/Menyu_IVANOVO_s_1_po_4_klass_dlya_monitoringa_pitaniya_RF.xls'},
  @{c='12 Прочие'; n='ПРАВО_Результаты_школьного_этапа_ВсОШ.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/PRAVO_Rezul_taty_shkol_nogo_etapa_VsOSh.pdf'},
  @{c='12 Прочие'; n='Примерное двухнедельное меню двухразового питания для детей с 1 по 4 класс (за 2026 год).pdf'; u='https://school56.gosuslugi.ru/netcat_files/49/484/menyu_12.01.26.pdf'},
  @{c='12 Прочие'; n='Примерное десятидневное меню для детей страдающих диабетом.xls'; u='https://school56.gosuslugi.ru/netcat_files/49/484/Primernoe_desyatidnevnoe_menyu_dlya_detey_stradayuschih_diabetom.xls'},
  @{c='12 Прочие'; n='рейтинг профиль на 2025-2026уч.г. гуманитарный.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/reyting_profil_na_2025_2026uch.g._gumanitarnyy_na_sayt.pdf'},
  @{c='12 Прочие'; n='рейтинг профиль на 2026-2027уч.г. технологический (инженерный).pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/reyting_inzhenernyy_profil_na_2026_2027uch.g._ot_30.07.2026_dlya_vystavleniya_na_sayt.pdf'},
  @{c='12 Прочие'; n='РУС_ЯЗЫК_Результаты_школьного_этапа_ВсОШ.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/RUS_YaZYK_Rezul_taty_shkol_nogo_etapa_VsOSh.pdf'},
  @{c='12 Прочие'; n='Физика_Результаты_школьного_этапа_ВсОШ.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Fizika.pdf'},
  @{c='13 Олимпиады'; n='Аналитический отчёт по школьному этапу ВСОШ в 2025-2026 учебном году.docx'; u='https://school56.gosuslugi.ru/netcat_files/32/50/analiticheskiy_otchet_2025.docx'},
  @{c='13 Олимпиады'; n='График проведения школьного этапа всероссийской олимпиады школьников в 2026-2027 учебном году.docx'; u='https://school56.gosuslugi.ru/netcat_files/32/50/GRAFIK.docx'},
  @{c='13 Олимпиады'; n='Общий_протокол_ВСОШ_школьный_этап_2025_2026_уч_год.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Obschiy_protokol_VSOSh_shkol_nyy_etap_2025_2026_uch_god.pdf'},
  @{c='13 Олимпиады'; n='Приказ о проведении школьного этапа всероссийской олимпиады школьников в 2026-2027 учебном году.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Prikaz_206_ot_01.09_VSOSh_she.pdf'},
  @{c='14 ГИА'; n='О правилах проведения ГИА-9.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Prikaz_o_formah_zayavleniy_prilozheniya.pdf'},
  @{c='14 ГИА'; n='Порядок подачи заявлений на участие в ГИА-11.docx'; u='https://school56.gosuslugi.ru/netcat_files/32/50/2._Poryadok_podachi_zayavleniy_na_uchastie_v_GIA.docx'},
  @{c='14 ГИА'; n='Приказ Департамента образования и науки Ивановской области от 10.12.2024 № 1394-о Об утверждении док.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/1._Prikaz_Departamenta_ot_10.12.2024_1394_o.pdf'},
  @{c='14 ГИА'; n='Приказ Департамента образования и науки Ивановской области № 118-о от 13.02.2026 « Об утверждении пу.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/PPE_osnovnogo_perioda.pdf'},
  @{c='14 ГИА'; n='Приказ Министерства просвещения Российской Федерации (Минпросвещения России) и Федеральной службы по.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/233_552.pdf'},
  @{c='14 ГИА'; n='Приказ об утверждении единого расписания и продолжительности проведения ЕГЭ по каждому предмету.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/RASPISANIE_EGE.pdf'},
  @{c='14 ГИА'; n='СПИСОК мест регистрации на сдачу ЕГЭ.docx'; u='https://school56.gosuslugi.ru/netcat_files/32/50/3._Mesta_registratsii.docx'},
  @{c='15 Охрана труда'; n='Перечень рекомендуемых мероприятий по улучшению условий труда.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/perechen_meropriyatiy.pdf'},
  @{c='15 Охрана труда'; n='Сводная ведомость результатов СОУТ 2026.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/svodnaya_vedomost_.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='0001202009110040.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/114/2992/0001202009110040.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='_306_ot_18.02.2025.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/114/2992/_306_ot_18.02.2025.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='Adaptirovannaya_OOP_NOO_variant_2.2.docx.docx'; u='https://school56.gosuslugi.ru/netcat_files/67/1847/Adaptirovannaya_OOP_NOO_variant_2.2.docx'},
  @{c='16 Файлы из других разделов сайта'; n='Adaptirovannaya_OOP_NOO_variant_2.2.docx (2).docx'; u='https://school56.gosuslugi.ru/netcat_files/67/3067/Adaptirovannaya_OOP_NOO_variant_2.2.docx'},
  @{c='16 Файлы из других разделов сайта'; n='Adaptirovannaya_OOP_NOO_variant_7.2.docx.docx'; u='https://school56.gosuslugi.ru/netcat_files/67/1847/Adaptirovannaya_OOP_NOO_variant_7.2.docx'},
  @{c='16 Файлы из других разделов сайта'; n='Adaptirovannaya_OOP_NOO_variant_7.2.docx (2).docx'; u='https://school56.gosuslugi.ru/netcat_files/67/3068/Adaptirovannaya_OOP_NOO_variant_7.2.docx'},
  @{c='16 Файлы из других разделов сайта'; n='Diplom_uchastie_v_munitsipal_nom_etape_Veselyy_svetofor.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/121/2990/Diplom_uchastie_v_munitsipal_nom_etape_Veselyy_svetofor.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='Kartochki_po_Kibierbiezopasnosti.zip.zip'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Kartochki_po_Kibierbiezopasnosti.zip'},
  @{c='16 Файлы из других разделов сайта'; n='Krynichka_24_26.doc.doc'; u='https://school56.gosuslugi.ru/netcat_files/67/3071/Krynichka_24_26.doc'},
  @{c='16 Файлы из других разделов сайта'; n='licenzia_2015.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/67/1847/licenzia_2015.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='n31loytagaiygjzv1gxrdg8w4pb2ngwx_1.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/userfiles/1/bezopasnost/n31loytagaiygjzv1gxrdg8w4pb2ngwx_1.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='NOO.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/67/1847/NOO.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='NOO.pdf (2).pdf'; u='https://school56.gosuslugi.ru/netcat_files/67/3066/NOO.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='OOP_OOO_2023.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/67/3002/OOP_OOO_2023.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='OOP_OOO_2025.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/67/1847/OOP_OOO_2025.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='OOP_OOO_2025.pdf (2).pdf'; u='https://school56.gosuslugi.ru/netcat_files/67/3002/OOP_OOO_2025.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='OOP_SOO_2025.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/67/1847/OOP_SOO_2025.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='OOP_SOO_2025.pdf (2).pdf'; u='https://school56.gosuslugi.ru/netcat_files/67/3070/OOP_SOO_2025.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='Pamyatka_dlya_naseleniya_pri_artobstrele.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/userfiles/1/bezopasnost/Pamyatka_dlya_naseleniya_pri_artobstrele.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='Pamyatka_dlya_roditeley_Bezopasnyy_put_do_shkoly_.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/121/2990/Pamyatka_dlya_roditeley_Bezopasnyy_put_do_shkoly_.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='Pamyatka_dlya_roditeley_voditeley_Ne_ostavlyayte_detey_v_salone_avtomobilya_.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/121/2990/Pamyatka_dlya_roditeley_voditeley_Ne_ostavlyayte_detey_v_salone_avtomobilya_.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='Pamyatka_minnaya_opasnost.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/userfiles/1/bezopasnost/Pamyatka_minnaya_opasnost.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='Pamyatka_Minprosvescheniya_Deystviya_pri_obnaruzhenii_beshoznogo_predmeta_.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/121/3069/Pamyatka_Minprosvescheniya_Deystviya_pri_obnaruzhenii_beshoznogo_predmeta_.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='Pamyatka_obuch.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Pamyatka_obuch.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='Pamyatka_protivopehotnye_miny.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/userfiles/1/bezopasnost/Pamyatka_protivopehotnye_miny.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='Pamyatka_rod.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/Pamyatka_rod.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='Pamyatka_voditelyam.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/121/2990/Pamyatka_voditelyam.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='Plan_antinarkoticheskogo_mesyachnika.docx.docx'; u='https://school56.gosuslugi.ru/netcat_files/173/3064/Plan_antinarkoticheskogo_mesyachnika.docx'},
  @{c='16 Файлы из других разделов сайта'; n='Plan_grafik_dorozhnaya_karta_meropriyatiy_.docx.docx'; u='https://school56.gosuslugi.ru/netcat_files/121/2990/Plan_grafik_dorozhnaya_karta_meropriyatiy_.docx'},
  @{c='16 Файлы из других разделов сайта'; n='Plan_raboty_otryada_YuID_na_2024_2025.docx.docx'; u='https://school56.gosuslugi.ru/netcat_files/121/2990/Plan_raboty_otryada_YuID_na_2024_2025.docx'},
  @{c='16 Файлы из других разделов сайта'; n='primer.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/primer.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='primer_0.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/primer_0.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='primer_1.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/primer_1.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='primer_2.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/primer_2.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='primer_3.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/32/50/primer_3.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='Programma_Diligenskaya_.doc.doc'; u='https://school56.gosuslugi.ru/netcat_files/67/3071/Programma_Diligenskaya_.doc'},
  @{c='16 Файлы из других разделов сайта'; n='Raspisanie_1_smena_25_26.xlsx.xlsx'; u='https://school56.gosuslugi.ru/netcat_files/24/2793/Raspisanie_1_smena_25_26.xlsx'},
  @{c='16 Файлы из других разделов сайта'; n='Raspisanie_2_smena_2025_26.xlsx.xlsx'; u='https://school56.gosuslugi.ru/netcat_files/24/2793/Raspisanie_2_smena_2025_26.xlsx'},
  @{c='16 Файлы из других разделов сайта'; n='Raspisanie_NOO.docx.docx'; u='https://school56.gosuslugi.ru/netcat_files/24/2793/Raspisanie_NOO.docx'},
  @{c='16 Файлы из других разделов сайта'; n='Reestrovaya_vypiska.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/67/1847/Reestrovaya_vypiska.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='reyting_estestv-nauchn._profil_na_2026-2027uch.g._ot_30.07.2026_dlya_vystavleniya_na_sayt.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/userfiles/reyting_estestv-nauchn._profil_na_2026-2027uch.g._ot_30.07.2026_dlya_vystavleniya_na_sayt.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='reyting_gumanitarn._profil_na_2026-2027uch.g._na_30.07.2026_dlya_vystavleniya_na_sayt.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/userfiles/reyting_gumanitarn._profil_na_2026-2027uch.g._na_30.07.2026_dlya_vystavleniya_na_sayt.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='reyting_inzhenernyy_profil_na_2026-2027uch.g._ot_30.07.2026_dlya_vystavleniya_na_sayt.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/userfiles/reyting_inzhenernyy_profil_na_2026-2027uch.g._ot_30.07.2026_dlya_vystavleniya_na_sayt.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='ShahmatyRabochaya_programma_KTP_2025_26.docx.docx'; u='https://school56.gosuslugi.ru/netcat_files/67/3071/ShahmatyRabochaya_programma_KTP_2025_26.docx'},
  @{c='16 Файлы из других разделов сайта'; n='Sovety_logopeda.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/110/7358/Sovety_logopeda.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='Test1.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/userfiles/1/Testi/Test1.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='Test2.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/userfiles/1/Testi/Test2.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='Test3.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/userfiles/1/Testi/Test3.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='Tipy_vzryvoopasnyh_predmetov.pdf.pdf'; u='https://school56.gosuslugi.ru/netcat_files/userfiles/1/bezopasnost/Tipy_vzryvoopasnyh_predmetov.pdf'},
  @{c='16 Файлы из других разделов сайта'; n='YuID_uchastie_v_konkurse.docx.docx'; u='https://school56.gosuslugi.ru/netcat_files/121/2990/YuID_uchastie_v_konkurse.docx'},
  @{c='16 Файлы из других разделов сайта'; n='Zayavlenie_na_zachislenie_v_10_klass.docx.docx'; u='https://school56.gosuslugi.ru/netcat_files/userfiles/Zayavlenie_na_zachislenie_v_10_klass.docx'}
)
$ok=0;$fail=0;$i=0
foreach($it in $items){
  $i++
  if(-not (Test-Path $it.c)){New-Item -ItemType Directory -Path $it.c | Out-Null}
  $p=Join-Path $it.c $it.n
  Write-Host ("[{0}/{1}] {2}" -f $i,$items.Count,$it.n)
  try{ Invoke-WebRequest -Uri $it.u -OutFile $p -UserAgent $UA -Headers @{Referer='https://school56.gosuslugi.ru/'} -TimeoutSec 120
       if((Get-Item $p).Length -gt 500){$ok++}else{$fail++;Remove-Item $p -Force} }
  catch{ $fail++; Write-Host '    -> ошибка' }
  Start-Sleep -Milliseconds 1500
}
Write-Host ''; Write-Host ("Готово. Скачано: {0}, не удалось: {1} из {2}." -f $ok,$fail,$items.Count)
