#!/usr/bin/env bash
# Скачивает все документы МБОУ «СШ № 56» в подпапки по категориям.
# Запуск:  bash 'Скачать всё (Linux, macOS).sh'
# Пауза 1.5 с между файлами — чтобы сайт не счёл это атакой.

set -u
UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0 Safari/537.36"
ok=0; fail=0; n=0; total=162

dl() {
  n=$((n+1))
  mkdir -p "$1"
  printf "[%%3d/%%3d] %%s\n" "$n" "$total" "$2"
  if curl -sL --max-time 120 -A "$UA" -e "https://school56.gosuslugi.ru/" -o "$1/$2" "$3"; then
    sz=$(wc -c < "$1/$2"); if [ "$sz" -gt 500 ]; then ok=$((ok+1)); else fail=$((fail+1)); rm -f "$1/$2"; echo "    -> пусто, пропущен"; fi
  else fail=$((fail+1)); echo "    -> ошибка"; fi
  sleep 1.5
}

dl "01 Основные документы" "Выписка из государственной информационной системы «Реестр организаций, осуществляющих образовательну.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Reestrovaya_vypiska.pdf"
dl "01 Основные документы" "Изменения и дополнения в коллективный договор №21 22 - 61 на 2025-2028 годы.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Izmeneniya_v_KD.pdf"
dl "01 Основные документы" "Календарный учебный график на 2025 - 2026 учебный год МБОУ «Средняя школа №56».docx" "https://school56.gosuslugi.ru/netcat_files/32/50/Kalendarnyy_grafik_25_26.docx"
dl "01 Основные документы" "Коллективный договор.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Kollektivnyy_dogovor_2025.pdf"
dl "01 Основные документы" "Лицензия на осуществление образовательной деятельности.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/licenzia_2015.pdf"
dl "01 Основные документы" "Правила внутреннего распорядка обучающихся.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/pol_o_pravilax_vro.pdf"
dl "01 Основные документы" "Правила внутреннего трудового распорядка.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Pravila_VNUTR_TRUD.RASPORYaDKA_NOVAYa_REDAKTsIYa.pdf"
dl "01 Основные документы" "Приказ о проведении школьного этапа ВсОШ 23 24.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Prikaz_209_OD_ob_organizatsii_shk_etapa_VSOSh_23_24.pdf"
dl "01 Основные документы" "Программа развития 2021-2026.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/programma_razvitiya_2021.pdf"
dl "01 Основные документы" "Устав образовательной организации.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Ustav_2025_podpisan_ETsP.pdf"
dl "01 Основные документы" "УЧЕБНЫЙ ПЛАН МБОУ «СШ № 56» на 2025 – 2026 учебный год.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/UChE_NYY_PLAN_2025_26_konstruktor.pdf"
dl "02 Публичные отчёты" "Публичный доклад за 2025-2026 учебный год.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/_Publichnyy_doklad_2025_2026.pdf"
dl "03 Финансово-хозяйственная деятельность" "Муниципальное задание на 2025 год.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/MZ_shkola_56_00000007_.pdf"
dl "03 Финансово-хозяйственная деятельность" "Отчет ФХД по итогам 2025 года.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Otchet_FHD_2025.pdf"
dl "03 Финансово-хозяйственная деятельность" "План финансово-хозяйственной деятельности на 2026 год.pdf" "https://school56.gosuslugi.ru/netcat_files/35/1620/plan_FHD_30.12.25.pdf"
dl "04 Защита персональных данных" "Политика в отношении обработки персональных данных.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Politika_v_otnoshenii_obrabotki_personal_nyh_dannyh2.pdf"
dl "05 Памятки" "Памятка для родителей о правильном питании школьников.pdf" "https://school56.gosuslugi.ru/netcat_files/105/2831/pamyatka_roditely.pdf"
dl "05 Памятки" "Памятка Правила здорового питания.pdf" "https://school56.gosuslugi.ru/netcat_files/105/2831/Pamyatka_Pravila_zdorovogo_pitaniya_dlya_shkolmznikov71b6e.pdf"
dl "05 Памятки" "Правила заполнения бланков ЕГЭ.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/10._pravila_zapolneniya_blankov_ege_v_2023_godu.pdf"
dl "05 Памятки" "Профилактика алкоголизма среди подростков.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Profilaktika_alk_uch.pdf"
dl "05 Памятки" "Профилактика подросткового суицида.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Profilaktika_rod.pdf"
dl "06 Федеральные" "Приказ Минпросвещения РФ об утверждении порядка проведения аттестации.docx" "https://school56.gosuslugi.ru/netcat_files/32/50/Prikaz_Minprosvescheniya_RF_ob_utverzhdenii_poryadka_provedeniya_attestatsii.docx"
dl "06 Федеральные" "Федеральный государственный образовательный стандарт дошкольного образования.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Federal_nyy_gosudarstvennyy_obrazovatel_nyy_standart_doshkol_nogo_obrazovaniya.pdf"
dl "07 Планы" "График оценочных процедур НОО 2 полугодие.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Grafik_otsenochnyh_protsedur_NOO_2_polugodie_23_24.pdf"
dl "07 Планы" "График оценочных процедур ООО 1 полугодие 2025-2026.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/GO_OOO_2025_2026_1_polugodie.pdf"
dl "07 Планы" "График оценочных процедур ООО 2 полугодие.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Graf_otsen_prots_OO_23_24_2polugod.pdf"
dl "07 Планы" "График оценочных процедур СОО 1 полугодие 2025-2026.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/GO_SOO_2025_2026_1_polugodie.pdf"
dl "07 Планы" "График оценочных процедур СОО 2 полугодие.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Grafik_otsen_prots_SO_23_24_2_polgod.pdf"
dl "07 Планы" "Календарный план воспитательной работы на 2024-2025 учебный год.docx" "https://school56.gosuslugi.ru/netcat_files/32/50/_nash_Kalendarnyy_plan_vospitatel_noy_raboty24_25_1_.docx"
dl "07 Планы" "Паспорт дорожной безопасности.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Pasport_dorozhnoy_bezopasnosti.pdf"
dl "07 Планы" "План внеурочной деятельности МБОУ СШ №56.docx" "https://school56.gosuslugi.ru/netcat_files/32/50/_plan_vneurochnoy_deyatel_nosti1_11.docx"
dl "07 Планы" "План мероприятий по профилактике экстремизма и терроризма.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Plan_meropriyatiy_po_profilaktike_extremizma_i_terrorizma.pdf"
dl "07 Планы" "ПЛАН ОРГАНИЗАЦИОННО-ТЕХНИЧЕСКИХ МЕРОПРИЯТИЙ ПО УЛУЧШЕНИЮ УСЛОВИЙ ОХРАНЫ ТРУДА, ЗДОРОВЬЯ РАБОТАЮЩИХ И.docx" "https://school56.gosuslugi.ru/netcat_files/32/50/Prikaz_200_od_ot_30.08.2024_Ob_utv._plana_OT_meropr._po_uluchsh._usl.OT.docx"
dl "07 Планы" "План проведения месячника антинаркотической направленности и популяризации здорового образа жизни в.docx" "https://school56.gosuslugi.ru/netcat_files/32/50/Plan_antinarkoticheskogo_mesyachnika.docx"
dl "07 Планы" "Приказ 198 Об организации работ по снижению документационной и бюрократической нагрузки на педагогич.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Prikaz_198_Ob_organizatsii_rabot_po_snizheniyu_dokumentatsionnoy_i_byurokraticheskoy_nagruzki_na_pedagogicheskih_rabotnikov.pdf"
dl "07 Планы" "Программа воспитания.docx" "https://school56.gosuslugi.ru/netcat_files/32/50/_nasha_programma_vospitaniya_shkoly56.docx"
dl "07 Планы" "Программа воспитательной работы летнего пришкольного оздоровительного лагеря с дневным пребыванием д.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Programma_vospitatel_noy_raboty_letnego_prishkol_nogo_ozdorovitel_nogo_lagerya_s_dnevnym_prebyvaniem_detey_56.pdf"
dl "07 Планы" "расписание кружков и секций на 2025-2026 учебный год.doc" "https://school56.gosuslugi.ru/netcat_files/32/50/raspisanie_kruzhkov_i_sektsiy_25_26.doc"
dl "07 Планы" "Типовой план по снижению документационной и бюрократической нагрузки на педагогических работников.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Tipovoy_plan_po_snizheniyu_dokumentatsionnoy_i_byurokraticheskoy_nagruzki_na_pedagogicheskih_rabotnikov.pdf"
dl "08 Отчёты" "Отчет о результатах самообследования за 2025 год.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/_Samoobsledovanie_za_2025.pdf"
dl "10 Локальные нормативные акты" "Планы по устранению недостатков, выявленных в ходе независимой оценки качества.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/test_file_18.pdf"
dl "10 Локальные нормативные акты" "Сведения о принятых по результатам проведения независимой оценки качества поощрительных мерах дисци.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/test_file_19.pdf"
dl "10 Локальные нормативные акты" "Договор о сотрудничестве с ИГХТУ.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Dogovor_shkola_IGHTU.pdf"
dl "10 Локальные нормативные акты" "Заявление на участие в индивидуальном отборе обучающихся в 10 класс.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/10_otbor.pdf"
dl "10 Локальные нормативные акты" "Заявление о приеме в 10 класс.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Zayavlenie_o_prieme_v_10_klass.pdf"
dl "10 Локальные нормативные акты" "Концепция информационной безопасности детей от 28.04.2023.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Kontseptsiya_ot_28.04.2023.pdf"
dl "10 Локальные нормативные акты" "Локальный нормативный акт о языках обучения.doc" "https://school56.gosuslugi.ru/netcat_files/32/50/polozh_iaz.doc"
dl "10 Локальные нормативные акты" "О мерах по обеспечению безопасности в период гололеда, образования наледи и сосулек на кровле школы.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Prikaz_08_OD_14.01.2025g._o_merah_po_obespechen.bezop.so_sl._pog.usl.GOLOLED.pdf"
dl "10 Локальные нормативные акты" "Образец заявления о приеме на обучение.docx" "https://school56.gosuslugi.ru/netcat_files/32/50/2026._Z_A_Ya_V_L_E_N_I_E_v_1_klass.docx"
dl "10 Локальные нормативные акты" "Педагогический состав 2026 по ОП.xlsx" "https://school56.gosuslugi.ru/netcat_files/171/3076/Kadry_na_sayt_2026_po_OP.xlsx"
dl "10 Локальные нормативные акты" "Педагогический состав НОО.pdf" "https://school56.gosuslugi.ru/netcat_files/171/3076/Kadry_na_sayt_2026_po_OP_NOO.pdf"
dl "10 Локальные нормативные акты" "Педагогический состав ООО.pdf" "https://school56.gosuslugi.ru/netcat_files/171/3076/Kadry_na_sayt_2026_po_OP_OOO.pdf"
dl "10 Локальные нормативные акты" "Педагогический состав СОО.pdf" "https://school56.gosuslugi.ru/netcat_files/171/3076/Kadry_na_sayt_2026_po_OP_SOO.pdf"
dl "10 Локальные нормативные акты" "Перечень юридических лиц и индивидуальных предпринимателей, оказывающих услуги по организации питани.xlsx" "https://school56.gosuslugi.ru/netcat_files/32/50/Perechen_yuridicheskih_lits_i_individual_nyh_predprinimateley.xlsx"
dl "10 Локальные нормативные акты" "Перечень юридических лиц и индивидуальных предпринимателей, поставляющих (реализующих) пищевые проду.xlsx" "https://school56.gosuslugi.ru/netcat_files/32/50/Perechen_yuridicheskih_lits_i_individual_nyh_predprinimateley_0.xlsx"
dl "10 Локальные нормативные акты" "План мероприятий по профилактике экстремизма.pdf" "https://school56.gosuslugi.ru/netcat_files/179/3093/plan_meropriyatiy_po_profilaktike_extremizma.pdf"
dl "10 Локальные нормативные акты" "положение об оказании ПОУ.doc" "https://school56.gosuslugi.ru/netcat_files/32/50/polozhenie_ob_okazanii_POU_novoe.doc"
dl "10 Локальные нормативные акты" "ПОЛОЖЕНИЕ О НАСТАВНИЧЕСТВЕ.docx" "https://school56.gosuslugi.ru/netcat_files/32/50/POLOZHENIE_O_NASTAVNICHESTVE.docx"
dl "10 Локальные нормативные акты" "Положение о порядке применения в МБОУ «СШ № 56» сервисов взаимодействия педагогических работников с.docx" "https://school56.gosuslugi.ru/netcat_files/32/50/Polozhenie_Sferum.docx"
dl "10 Локальные нормативные акты" "Положение о режиме занятий обучающихся.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/p_rezhim_obuh_2018.pdf"
dl "10 Локальные нормативные акты" "Положение о системе видеонаблюдения.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Polozhenie_o_sisteme_videonablyudeniya.pdf"
dl "10 Локальные нормативные акты" "Положение об очно-заочной форме обучения.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Polozhenie_ob_ochno_zaochnoy_forme_obucheniya.pdf"
dl "10 Локальные нормативные акты" "Положение об электронном обучении и использовании дистанционных образовательных технологий в образов.docx" "https://school56.gosuslugi.ru/netcat_files/32/50/Polozhenie_ob_organizacii_obrazovatelnogo_processa_s_primeneniem_ehlektronnogo_obucheniya.docx"
dl "10 Локальные нормативные акты" "Порядок и основания перевода, отчисления и восстановления обучающихся.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/pol_o_poryadke_perevoda_otcisteniya.pdf"
dl "10 Локальные нормативные акты" "Порядок оформления возникновения, приостановления и прекращения отношений между образовательной орга.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/pol_o_poryadke_perevoda_otcisteniya_0.pdf"
dl "10 Локальные нормативные акты" "Порядок проведения ГИА-9.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Poryadok_GIA9_2023.pdf"
dl "10 Локальные нормативные акты" "Правила подачи апелляции.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Podacha_appelyatsii_v_2023g.pdf"
dl "10 Локальные нормативные акты" "Правила приема обучающихся.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/pravila_priema_22.pdf"
dl "10 Локальные нормативные акты" "ПРАВИЛА приема обучающихся в муниципальное бюджетное общеобразовательное учреждение «Средняя школа №.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/2._Pravila_priema_obuchayuschihsya_2023_2024_2_.pdf"
dl "10 Локальные нормативные акты" "Предписания контрольно-надзорных органов, отчеты об их исполнении.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/akt_rpnz_170.pdf"
dl "10 Локальные нормативные акты" "Приказ на изменение в положение об оплате учителей с 01.03.2025.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Prikaz_na_izmenenie_v_polozhenie_ob_olate_uchiteley_s_01.03.2025.pdf"
dl "10 Локальные нормативные акты" "Приказ о внесении изменений в Положение о пропускном режиме.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Prikaz_o_vnesenii_izmeneniy_v_Polozhenie_o_propusknom_rezhime.pdf"
dl "10 Локальные нормативные акты" "Приказ О сроках проведения индивидуального отбора в профильный класс в МБОУ «СШ № 56» для получения.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Prikaz_priem_v_10_klass.pdf"
dl "10 Локальные нормативные акты" "Приказ об утверждении региональных инновационных площадок.pdf" "https://school56.gosuslugi.ru/netcat_files/180/3092/RIP_2026.pdf"
dl "10 Локальные нормативные акты" "Проведение Всероссийских проверочных работ (ВПР).pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Poryadok_provedeniya_vserossiyskih_proverochnyh_rabot_v_2023_godu.pdf"
dl "10 Локальные нормативные акты" "Распорядительный акт о закреплении организации за конкретными территориями.doc" "https://school56.gosuslugi.ru/netcat_files/32/50/postanovlenie_21.01.2013_o_zakreplenii_mikrouchastkov.doc"
dl "10 Локальные нормативные акты" "Указ президента Российской Федерации «Об утверждении доктрины информационной безопасности Российской.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Ukaz.pdf"
dl "10 Локальные нормативные акты" "Федеральный государственный образовательный стандарт начального общего образования.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Federal_nyy_gosudarstvennyy_obrazovatel_nyy_standart_nachal_nogo_obschego_obrazovaniya.docx.pdf"
dl "10 Локальные нормативные акты" "Федеральный государственный образовательный стандарт основного общего образования.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Federal_nyy_gosudarstvennyy_obrazovatel_nyy_standart_osnovnogo_obschego_obrazovaniya.pdf"
dl "10 Локальные нормативные акты" "Федеральный государственный образовательный стандарт среднего общего образования.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Federal_nyy_gosudarstvennyy_obrazovatel_nyy_standart_srednego_obschego_obrazovaniya.pdf"
dl "10 Локальные нормативные акты" "Федеральный закон «О персональных данных».pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/152fz_O_persrnal_nyh_dannyh.pdf"
dl "10 Локальные нормативные акты" "Форма апелляции о несогласии с выставленными баллами.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Forma_apellyatsii_o_nesoglasii_s_vystavlennymi_ballami.pdf"
dl "10 Локальные нормативные акты" "Формы, периодичность и порядок текущего контроля успеваемости и промежуточной аттестации обучающихся.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/polojenit_usp_2022.pdf"
dl "10 Локальные нормативные акты" "ЭКОНОМИКА_Результаты_школьного_этапа_ВсОШ.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/EKONOMIKA_Rezul_taty_shkol_nogo_etapa_VsOSh.pdf"
dl "11 Платные образовательные услуги" "Образец договора об оказании платных образовательных услуг.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/dogovor22.pdf"
dl "11 Платные образовательные услуги" "Порядок оказания платных образовательных услуг.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/polog_pou_22.pdf"
dl "11 Платные образовательные услуги" "Утверждение стоимости обучения (по каждой образовательной программе).jpg" "https://school56.gosuslugi.ru/netcat_files/32/50/cci13122022_0002.jpg"
dl "12 Прочие" "Английский язык_Результаты_школьного_этапа_ВсОШ.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Angliyskiy_yazyk.pdf"
dl "12 Прочие" "География_Результаты_школьного_этапа_ВсОШ.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Geografiya.pdf"
dl "12 Прочие" "Литература_Результаты_школьного_этапа_ВсОШ.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Literatura.pdf"
dl "12 Прочие" "Меню приготавливаемых блюд для детей с 1 по 4 класс.xls" "https://school56.gosuslugi.ru/netcat_files/49/484/Menyu_IVANOVO_s_1_po_4_klass_dlya_monitoringa_pitaniya_RF.xls"
dl "12 Прочие" "ПРАВО_Результаты_школьного_этапа_ВсОШ.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/PRAVO_Rezul_taty_shkol_nogo_etapa_VsOSh.pdf"
dl "12 Прочие" "Примерное двухнедельное меню двухразового питания для детей с 1 по 4 класс (за 2026 год).pdf" "https://school56.gosuslugi.ru/netcat_files/49/484/menyu_12.01.26.pdf"
dl "12 Прочие" "Примерное десятидневное меню для детей страдающих диабетом.xls" "https://school56.gosuslugi.ru/netcat_files/49/484/Primernoe_desyatidnevnoe_menyu_dlya_detey_stradayuschih_diabetom.xls"
dl "12 Прочие" "рейтинг профиль на 2025-2026уч.г. гуманитарный.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/reyting_profil_na_2025_2026uch.g._gumanitarnyy_na_sayt.pdf"
dl "12 Прочие" "рейтинг профиль на 2026-2027уч.г. технологический (инженерный).pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/reyting_inzhenernyy_profil_na_2026_2027uch.g._ot_30.07.2026_dlya_vystavleniya_na_sayt.pdf"
dl "12 Прочие" "РУС_ЯЗЫК_Результаты_школьного_этапа_ВсОШ.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/RUS_YaZYK_Rezul_taty_shkol_nogo_etapa_VsOSh.pdf"
dl "12 Прочие" "Физика_Результаты_школьного_этапа_ВсОШ.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Fizika.pdf"
dl "13 Олимпиады" "Аналитический отчёт по школьному этапу ВСОШ в 2025-2026 учебном году.docx" "https://school56.gosuslugi.ru/netcat_files/32/50/analiticheskiy_otchet_2025.docx"
dl "13 Олимпиады" "График проведения школьного этапа всероссийской олимпиады школьников в 2026-2027 учебном году.docx" "https://school56.gosuslugi.ru/netcat_files/32/50/GRAFIK.docx"
dl "13 Олимпиады" "Общий_протокол_ВСОШ_школьный_этап_2025_2026_уч_год.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Obschiy_protokol_VSOSh_shkol_nyy_etap_2025_2026_uch_god.pdf"
dl "13 Олимпиады" "Приказ о проведении школьного этапа всероссийской олимпиады школьников в 2026-2027 учебном году.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Prikaz_206_ot_01.09_VSOSh_she.pdf"
dl "14 ГИА" "О правилах проведения ГИА-9.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Prikaz_o_formah_zayavleniy_prilozheniya.pdf"
dl "14 ГИА" "Порядок подачи заявлений на участие в ГИА-11.docx" "https://school56.gosuslugi.ru/netcat_files/32/50/2._Poryadok_podachi_zayavleniy_na_uchastie_v_GIA.docx"
dl "14 ГИА" "Приказ Департамента образования и науки Ивановской области от 10.12.2024 № 1394-о Об утверждении док.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/1._Prikaz_Departamenta_ot_10.12.2024_1394_o.pdf"
dl "14 ГИА" "Приказ Департамента образования и науки Ивановской области № 118-о от 13.02.2026 « Об утверждении пу.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/PPE_osnovnogo_perioda.pdf"
dl "14 ГИА" "Приказ Министерства просвещения Российской Федерации (Минпросвещения России) и Федеральной службы по.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/233_552.pdf"
dl "14 ГИА" "Приказ об утверждении единого расписания и продолжительности проведения ЕГЭ по каждому предмету.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/RASPISANIE_EGE.pdf"
dl "14 ГИА" "СПИСОК мест регистрации на сдачу ЕГЭ.docx" "https://school56.gosuslugi.ru/netcat_files/32/50/3._Mesta_registratsii.docx"
dl "15 Охрана труда" "Перечень рекомендуемых мероприятий по улучшению условий труда.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/perechen_meropriyatiy.pdf"
dl "15 Охрана труда" "Сводная ведомость результатов СОУТ 2026.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/svodnaya_vedomost_.pdf"
dl "16 Файлы из других разделов сайта" "0001202009110040.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/114/2992/0001202009110040.pdf"
dl "16 Файлы из других разделов сайта" "_306_ot_18.02.2025.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/114/2992/_306_ot_18.02.2025.pdf"
dl "16 Файлы из других разделов сайта" "Adaptirovannaya_OOP_NOO_variant_2.2.docx.docx" "https://school56.gosuslugi.ru/netcat_files/67/1847/Adaptirovannaya_OOP_NOO_variant_2.2.docx"
dl "16 Файлы из других разделов сайта" "Adaptirovannaya_OOP_NOO_variant_2.2.docx (2).docx" "https://school56.gosuslugi.ru/netcat_files/67/3067/Adaptirovannaya_OOP_NOO_variant_2.2.docx"
dl "16 Файлы из других разделов сайта" "Adaptirovannaya_OOP_NOO_variant_7.2.docx.docx" "https://school56.gosuslugi.ru/netcat_files/67/1847/Adaptirovannaya_OOP_NOO_variant_7.2.docx"
dl "16 Файлы из других разделов сайта" "Adaptirovannaya_OOP_NOO_variant_7.2.docx (2).docx" "https://school56.gosuslugi.ru/netcat_files/67/3068/Adaptirovannaya_OOP_NOO_variant_7.2.docx"
dl "16 Файлы из других разделов сайта" "Diplom_uchastie_v_munitsipal_nom_etape_Veselyy_svetofor.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/121/2990/Diplom_uchastie_v_munitsipal_nom_etape_Veselyy_svetofor.pdf"
dl "16 Файлы из других разделов сайта" "Kartochki_po_Kibierbiezopasnosti.zip.zip" "https://school56.gosuslugi.ru/netcat_files/32/50/Kartochki_po_Kibierbiezopasnosti.zip"
dl "16 Файлы из других разделов сайта" "Krynichka_24_26.doc.doc" "https://school56.gosuslugi.ru/netcat_files/67/3071/Krynichka_24_26.doc"
dl "16 Файлы из других разделов сайта" "licenzia_2015.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/67/1847/licenzia_2015.pdf"
dl "16 Файлы из других разделов сайта" "n31loytagaiygjzv1gxrdg8w4pb2ngwx_1.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/userfiles/1/bezopasnost/n31loytagaiygjzv1gxrdg8w4pb2ngwx_1.pdf"
dl "16 Файлы из других разделов сайта" "NOO.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/67/1847/NOO.pdf"
dl "16 Файлы из других разделов сайта" "NOO.pdf (2).pdf" "https://school56.gosuslugi.ru/netcat_files/67/3066/NOO.pdf"
dl "16 Файлы из других разделов сайта" "OOP_OOO_2023.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/67/3002/OOP_OOO_2023.pdf"
dl "16 Файлы из других разделов сайта" "OOP_OOO_2025.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/67/1847/OOP_OOO_2025.pdf"
dl "16 Файлы из других разделов сайта" "OOP_OOO_2025.pdf (2).pdf" "https://school56.gosuslugi.ru/netcat_files/67/3002/OOP_OOO_2025.pdf"
dl "16 Файлы из других разделов сайта" "OOP_SOO_2025.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/67/1847/OOP_SOO_2025.pdf"
dl "16 Файлы из других разделов сайта" "OOP_SOO_2025.pdf (2).pdf" "https://school56.gosuslugi.ru/netcat_files/67/3070/OOP_SOO_2025.pdf"
dl "16 Файлы из других разделов сайта" "Pamyatka_dlya_naseleniya_pri_artobstrele.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/userfiles/1/bezopasnost/Pamyatka_dlya_naseleniya_pri_artobstrele.pdf"
dl "16 Файлы из других разделов сайта" "Pamyatka_dlya_roditeley_Bezopasnyy_put_do_shkoly_.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/121/2990/Pamyatka_dlya_roditeley_Bezopasnyy_put_do_shkoly_.pdf"
dl "16 Файлы из других разделов сайта" "Pamyatka_dlya_roditeley_voditeley_Ne_ostavlyayte_detey_v_salone_avtomobilya_.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/121/2990/Pamyatka_dlya_roditeley_voditeley_Ne_ostavlyayte_detey_v_salone_avtomobilya_.pdf"
dl "16 Файлы из других разделов сайта" "Pamyatka_minnaya_opasnost.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/userfiles/1/bezopasnost/Pamyatka_minnaya_opasnost.pdf"
dl "16 Файлы из других разделов сайта" "Pamyatka_Minprosvescheniya_Deystviya_pri_obnaruzhenii_beshoznogo_predmeta_.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/121/3069/Pamyatka_Minprosvescheniya_Deystviya_pri_obnaruzhenii_beshoznogo_predmeta_.pdf"
dl "16 Файлы из других разделов сайта" "Pamyatka_obuch.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Pamyatka_obuch.pdf"
dl "16 Файлы из других разделов сайта" "Pamyatka_protivopehotnye_miny.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/userfiles/1/bezopasnost/Pamyatka_protivopehotnye_miny.pdf"
dl "16 Файлы из других разделов сайта" "Pamyatka_rod.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/Pamyatka_rod.pdf"
dl "16 Файлы из других разделов сайта" "Pamyatka_voditelyam.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/121/2990/Pamyatka_voditelyam.pdf"
dl "16 Файлы из других разделов сайта" "Plan_antinarkoticheskogo_mesyachnika.docx.docx" "https://school56.gosuslugi.ru/netcat_files/173/3064/Plan_antinarkoticheskogo_mesyachnika.docx"
dl "16 Файлы из других разделов сайта" "Plan_grafik_dorozhnaya_karta_meropriyatiy_.docx.docx" "https://school56.gosuslugi.ru/netcat_files/121/2990/Plan_grafik_dorozhnaya_karta_meropriyatiy_.docx"
dl "16 Файлы из других разделов сайта" "Plan_raboty_otryada_YuID_na_2024_2025.docx.docx" "https://school56.gosuslugi.ru/netcat_files/121/2990/Plan_raboty_otryada_YuID_na_2024_2025.docx"
dl "16 Файлы из других разделов сайта" "primer.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/primer.pdf"
dl "16 Файлы из других разделов сайта" "primer_0.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/primer_0.pdf"
dl "16 Файлы из других разделов сайта" "primer_1.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/primer_1.pdf"
dl "16 Файлы из других разделов сайта" "primer_2.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/primer_2.pdf"
dl "16 Файлы из других разделов сайта" "primer_3.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/32/50/primer_3.pdf"
dl "16 Файлы из других разделов сайта" "Programma_Diligenskaya_.doc.doc" "https://school56.gosuslugi.ru/netcat_files/67/3071/Programma_Diligenskaya_.doc"
dl "16 Файлы из других разделов сайта" "Raspisanie_1_smena_25_26.xlsx.xlsx" "https://school56.gosuslugi.ru/netcat_files/24/2793/Raspisanie_1_smena_25_26.xlsx"
dl "16 Файлы из других разделов сайта" "Raspisanie_2_smena_2025_26.xlsx.xlsx" "https://school56.gosuslugi.ru/netcat_files/24/2793/Raspisanie_2_smena_2025_26.xlsx"
dl "16 Файлы из других разделов сайта" "Raspisanie_NOO.docx.docx" "https://school56.gosuslugi.ru/netcat_files/24/2793/Raspisanie_NOO.docx"
dl "16 Файлы из других разделов сайта" "Reestrovaya_vypiska.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/67/1847/Reestrovaya_vypiska.pdf"
dl "16 Файлы из других разделов сайта" "reyting_estestv-nauchn._profil_na_2026-2027uch.g._ot_30.07.2026_dlya_vystavleniya_na_sayt.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/userfiles/reyting_estestv-nauchn._profil_na_2026-2027uch.g._ot_30.07.2026_dlya_vystavleniya_na_sayt.pdf"
dl "16 Файлы из других разделов сайта" "reyting_gumanitarn._profil_na_2026-2027uch.g._na_30.07.2026_dlya_vystavleniya_na_sayt.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/userfiles/reyting_gumanitarn._profil_na_2026-2027uch.g._na_30.07.2026_dlya_vystavleniya_na_sayt.pdf"
dl "16 Файлы из других разделов сайта" "reyting_inzhenernyy_profil_na_2026-2027uch.g._ot_30.07.2026_dlya_vystavleniya_na_sayt.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/userfiles/reyting_inzhenernyy_profil_na_2026-2027uch.g._ot_30.07.2026_dlya_vystavleniya_na_sayt.pdf"
dl "16 Файлы из других разделов сайта" "ShahmatyRabochaya_programma_KTP_2025_26.docx.docx" "https://school56.gosuslugi.ru/netcat_files/67/3071/ShahmatyRabochaya_programma_KTP_2025_26.docx"
dl "16 Файлы из других разделов сайта" "Sovety_logopeda.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/110/7358/Sovety_logopeda.pdf"
dl "16 Файлы из других разделов сайта" "Test1.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/userfiles/1/Testi/Test1.pdf"
dl "16 Файлы из других разделов сайта" "Test2.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/userfiles/1/Testi/Test2.pdf"
dl "16 Файлы из других разделов сайта" "Test3.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/userfiles/1/Testi/Test3.pdf"
dl "16 Файлы из других разделов сайта" "Tipy_vzryvoopasnyh_predmetov.pdf.pdf" "https://school56.gosuslugi.ru/netcat_files/userfiles/1/bezopasnost/Tipy_vzryvoopasnyh_predmetov.pdf"
dl "16 Файлы из других разделов сайта" "YuID_uchastie_v_konkurse.docx.docx" "https://school56.gosuslugi.ru/netcat_files/121/2990/YuID_uchastie_v_konkurse.docx"
dl "16 Файлы из других разделов сайта" "Zayavlenie_na_zachislenie_v_10_klass.docx.docx" "https://school56.gosuslugi.ru/netcat_files/userfiles/Zayavlenie_na_zachislenie_v_10_klass.docx"

echo; echo "Готово. Скачано: $ok, не удалось: $fail из $total."
